// ignore_for_file: file_names
final Map<String, String> foodAdditives = {
  "e100":"Curcumin",
  "e101":"Riboflavin",
  "e102":"Tartrazine",
  "e104":"Quinoline yellow",
  "e110":"Sunset Yellow FCF",
  "e120": "Cochineal",
  "e122": "Azorubine",
  "e123" :"Amaranth",
  "e124":"Cochineal Red A",
  "e127":"Erythrosine",
  "e129":"Allura Red AC",
  "e131":"Patent Blue V",
  "e132":"lndigotine",
  "e133":"Brilliant Blue FCF",
  "e140": "Chlorophylls and chlorophyllins",
  "e141": "Copper complexes of chlorophyll and chlorophyllins",
  "e142": "Green S",
  "e150a" :"Plain caramel",
  "e150b" :"Caustic sulphite caramel",
  "e150c" :"Ammonia caramel",
  "e150d": "Sulphite ammonia caramel",
  "e151": "Brilliant Black BN",
  "e153": "Vegetable carbon",
  "e155": "Brown HT",
  "e160a": "Carotenes",
  "e160b":"Annatto",
  "e160c": "Capsorubin",
  "e160d": "Lycopene",
  "e160e": "Beta-apo-8'-carotenal (C30)",
  "e161b": "Lutein",
  "e161g": "Canthaxanthin",
  "e162": "Beetroot Red",
  "e163": "Anthocyanins",
  "e170": "Calcium carbonate",
  "e171": "Titanium dioxide",
  "e172": "Iron oxides and hydroxides",
  "e173": "Aluminium",
  "e174": "Silver",
  "e175": "Gold",
  "e180": "Litholrubine BK",
  "e200": "Sorbic acid",
  "e202": "Potassium sorbate",
  "e210": "Benzoic acid",
  "e211": "Sodium benzoate",
  "e212": "Potassium benzoate",
  "e213": "Calcium benzoate",
  "e214": "Ethyl p-hydroxybenzoate",
  "e215": "Sodium ethyl p-hydroxybenzoate",
  "e218": "Methyl p-hydroxybenzoate",
  "e219": "Sodium methyl p-hydroxybenzoate",
  "e220": "Sulphur dioxide",
  "e221": "Sodium sulphite",
  "e222": "Sodium hydrogen sulphite",
  "e223": "Sodium metabisulphite",
  "e224": "Potassium metabisulphite",
  "e226": "Calcium sulphite",
  "e227": "Calcium hydrogen sulphite",
  "e228": "Potassium hydrogen sulphite",
  "e234": "Nisin",
  "e235": "Natamycin",
  "e239": "Hexamethylene tetramine",
  "e242": "Dimethyl dicarbonate",
  "e243": "Ethyl lauroyl arginate",
  "e249": "Potassium nitrite",
  "e250": "Sodium nitrite",
  "e251": "Sodium nitrate",
  "e252": "Potassium nitrate",
  "e280": "Propionic acid",
  "e281": "Sodium propionate",
  "e282": "Calcium propionate",
  "e283": "Potassium propionate",
  "e284": "Boric acid",
  "e285": "Sodium tetraborate",
  "e1105": "Lysozyme",
  "e300": "Ascorbic acid",
  "e301": "Sodium ascorbate",
  "e302": "Calcium ascorbate",
  "e304": "Fatty acid esters of ascorbic acid",
  "e306": "Tocopherols",
  "e307": "Alpha-tocopherol",
  "e308": "Gamma-tocopherol",
  "e309": "Delta-tocopherol",
  "e310": "Propyl gallate",
  "e315": "Erythorbic acid",
  "e316": "Sodium erythorbate",
  "e319": "Tertiary-butyl hydroquinone",
  "e320": "Butylated hydroxyanisole",
  "e321": "Butylated hydroxytoluene",
  "e392": "Extracts of rosemary",
  "e586": "4-Hexylresorcinol",
  "e420": "Sorbitol",
  "e421": "Mannitol",
  "e950": "Acesulfame K",
  "e951": "Aspartame",
  "e952": "Cyclamic acid",
  "e953": "lsomalt",
  "e954": "Saccharin",
  "e955": "Sucralose",
  "e957": "Thaumatin",
  "e959": "Neohesperidine DC",
  "e960": "Steviol glycoside",
  "e961": "Neotame",
  "e962": "Salt of aspartame-acesulfame",
  "e964": "Polyglycitol syrup",
  "e965": "Maltitol",
  "e966": "Lactitol",
  "e967": "Xylitol",
  "e968": "Erythritol",
  "e969": "Advantame",
  "e322": "Lecithins",
  "e400": "Alginic acid",
  "e401": "Sodium alginate",
  "e402": "Potassium alginate",
  "e403": "Ammonium alginate",
  "e404": "Calcium alginate",
  "e405": "Propane-1",
  "e406": "Agar",
  "e407": "Carrageenan",
  "e407a": "Processed eucheuma seaweed",
  "e410": "Locust bean gum",
  "e412": "Guar gum",
  "e413": "Tragacanth",
  "e414" :"Acacia gum",
  "e415" :"Xanthan gum",
  "e416" :"Karaya gum",
  "e417" :"Tara gum",
  "e418" :"Gellan gum",
  "e425" :"Konjac",
  "e426" :"Soybean hemicellulose",
  "e427" :"Cassia gum",
  "e432" :"Polyoxyethylene sorbitan monolaurate",
  "e433" :"Polyoxyethylene sorbitan mono-oleate",
  "e434" :"Polyoxyethylene sorbitan monopalmitate",
  "e435" :"Polyoxyethylene sorbitan monostearate",
  "e436" :"Polyoxyethylene sorbitan tristearate",
  "e440" :"Pectins",
  "e442" :"Ammonium phosphatides",
  "e444" :"Sucrose acetate isobutyrate",
  "e445" :"Glycerol esters of wood rosins",
  "e460" :"Cellulose",
  "e461" :"Methyl cellulose",
  "e462" :"Ethyl cellulose",
  "e463" :"Hydroxypropyl cellulose",
  "e464" :"Hydroxypropyl methyl cellulose",
  "e465" :"Ethyl methyl cellulose",
  "e466" :"Carboxy methyl cellulose",
  "e468" :"Crosslinked sodium carboxy methyl cellulose",
  "e469" :"Enzymatically hydrolysed carboxy methyl cellulose",
  "e470a" :"Sodium, potassium and calcium salts of fatty acids",
  "e470b" :"Magnesium salts of fatty acids",
  "e471" :"diglycerides",
  "e472a" :"Acetic acid esters of mono- and diglycerides of fatty acids",
  "e472b" :"Lactic acid esters of mono- and diglycerides of fatty acids",
  "e472c" :"Citric acid esters of mono- and diglycerides of fatty acids",
  "e472d" :"Tartaric acid esters of mono- and diglycerides of fatty acids",
  "e472e" :"Mono- and diacetyltartaric acid esters of monoand diglycerides of fatty acids",
  "e472f" :"Mixed acetic and tartaric acid esters of monoand diglycerides of fatty acids",
  "e473" :"Sucrose esters of fatty acids",
  "e474" :"Sucroglycerides",
  "e475" :"Polyglycerol esters of fatty acids",
  "e476" :"Polyglycerol polyricinoleate",
  "e477" :"Propane-1,2-diol esters of fatty acids",
  "e479b": "Thermally oxidised soya bean oil interacted with mono and diglycerides of fatty acids",
  "e481" :"Sodium stearoyl-2-lactylate",
  "e482" :"Calcium stearoyl-2-lactylate",
  "e483" :"Stearyl tartrate",
  "e491" :"Sorbitan monostearate",
  "e492" :"Sorbitan tristearate",
  "e493" :"Sorbitan monolaurate",
  "e494" :"Sorbitan monooleate",
  "e495" :"Sorbitan monopalmitate",
  "e1103": "Invertase",
  "e260" :"Acetic acid",
  "e261" :"Potassium acetate",
  "e262" :"Sodium acetate",
  "e263" :"Calcium acetate",
  "e270" :"Lactic acid",
  "e290" :"Carbon dioxide",
  "e296" :"Malic acid",
  "e297" :"Fumaric acid",
  "e325" :"Sodium lactate",
  "e326" :"Potassium lactate",
  "e327" :"Calcium lactate",
  "e330" :"Citric acid",
  "e331" :"Sodium citrates",
  "e332" :"Potassium citrates",
  "e333" :"Calcium citrates",
  "e334" :"Tartaric acid",
  "e335" :"Sodium tartrates",
  "e336" :"Potassium tartrates",
  "e337" :"Sodium potassium tartrate",
  "e338" :"Phosphoric acid",
  "e339" :"Sodium phosphates",
  "e340" :"Potassium phosphates",
  "e341" :"Calcium phosphates",
  "e343" :"Magnesium phosphates",
  "e350" :"Sodium malates",
  "e351" :"Potassium malate",
  "e352" :"Calcium malates",
  "e353" :"Metatartaric acid",
  "e354" :"Calcium tartrate",
  "e355" :"Adipic acid",
  "e356" :"Sodium adipate",
  "e357" :"Potassium adipate",
  "e363" :"Succinic acid",
  "e380" :"Triammonium citrate",
  "e385" :"Calcium disodium ethylene",
  "e422" :"Glycerol",
  "e423" :"Octenyl succinic acid",
  "e450" :"Diphosphates",
  "e451" :"Triphosphates",
  "e452" :"Polyphosphates",
  "e459" :"Beta-cyclodextrin",
  "e499" :"Stigmasterol-rich plant sterols",
  "e500" :"Sodium carbonates",
  "e501" :"Potassium carbonates",
  "e503" :"Ammonium carbonates",
  "e504" :"Magnesium carbonates",
  "e507" :"Hydrochloric acid",
  "e508" :"Potassium chloride",
  "e509" :"Calcium chloride",
  "e511" :"Magnesium chloride",
  "e512" :"Stannous chloride",
  "e513" :"Sulphuric acid",
  "e514" :"Sodium sulphates",
  "e515" :"Potassium sulphates",
  "e516" :"Calcium sulphate",
  "e517" :"Ammonium sulphate",
  "e520" :"Aluminium sulphate",
  "e521" :"Aluminium sodium sulphate",
  "e522" :"Aluminium potassium sulphate",
  "e523" :"Aluminium ammonium sulphate",
  "e524" :"Sodium hydroxide",
  "e525" :"Potassium hydroxide",
  "e526" :"Calcium hydroxide",
  "e527" :"Ammonium hydroxide",
  "e528" :"Magnesium hydroxide",
  "e529" :"Calcium oxide",
  "e530" :"Magnesium oxide",
  "e535" :"Sodium ferrocyanide",
  "e536" :"Potassium ferrocyanide",
  "e538" :"Calcium ferrocyanide",
  "e541" :"Sodium aluminium phosphate",
  "e551" :"Silicon dioxide",
  "e552" :"Calcium silicate",
  "e553a": "Magnesium" ,
  "e553b" :"Talc",
  "e554" :"Sodium aluminium silicate",
  "e555" :"Potassium aluminium silicate",
  "e570" :"Fatty acids",
  "e574" :"Gluconic acid",
  "e575" :"Glucono delta-lactone",
  "e576" :"Sodium gluconate",
  "e577" :"Potassium gluconate",
  "e578" :"Calcium gluconate",
  "e579" :"Ferrous gluconate",
  "e585" :"Ferrous lactate",
  "e620" :"Glutamic acid",
  "e621" :"Monosodium glutamate",
  "e622" :"Monopotassium glutamate",
  "e623" :"Calcium diglutamate",
  "e624" :"Monoammonium glutamate",
  "e625" :"Magnesium diglutamate",
  "e626" :"Guanylic acid",
  "e627" :"Disodium guanylate",
  "e628" :"Dipotassium guanylate",
  "e629" :"Calcium guanylate",
  "e630" :"lnosinic acid",
  "e631" :"Disodium inosinate",
  "e632" :"Dipotassium inosinate",
  "e633" :"Calcium inosinate",
  "e634" :"Calcium 5'-ribonucleotides",
  "e635" :"Disodium 5'-ribonucleotides",
  "e640" :"Glycine",
  "e641" :"L-leucine",
  "e650" :"Zinc acetate",
  "e900" :"Dimethylpolysiloxane",
  "e901" :"Beeswax",
  "e902" :"Candelilla wax",
  "e903" :"Carnauba wax",
  "e904" :"Shellac",
  "e905" :"Microcrystalline wax",
  "e907" :"Hydrogenated Poly-1-Decene",
  "e914" :"Oxidised Polyethylene wax",
  "e920" :"L-Cysteine",
  "e927b" :"Carbamide",
  "e938" :"Argon",
  "e939" :"Helium",
  "e941" :"Nitrogen",
  "e942" :"Nitrous oxide",
  "e943a" :"Butane",
  "e943b" :"Iso-butane",
  "e944" :"Propane",
  "e948" :"Oxygen",
  "e949" :"Hydrogen",
  "e999" :"Quillaia extract",
  "e1200" :"Polydextrose",
  "e1201" :"Polyvinylpyrrolidone",
  "e1202" :"Polyvinylpolypyrrolidone",
  "e1203" :"Polyvinyl alcohol",
  "e1204" :"Pullulan",
  "e1205" :"Basic methacrylate copolymer",
  "e1206" :"Neutral methacrylate copolymer",
  "e1207" :"Anionic methacrylate copolymer",
  "e1208" :"Polyvinylpyrrolidone-vinyl acetate copolymer",
  "e1209" :"Polyvinyl alcohol-polyethylene glycol-graft- co-polymer",
  "e1404" :"Oxidised starch",
  "e1410" :"Monostarch phosphate",
  "e1412" :"Distarch phosphate",
  "e1413" :"Phosphated distarch phosphate",
  "e1414" :"Acetylated distarch phosphate",
  "e1420" :"Acetylated starch",
  "e1422" :"Acetylated distarch adipate",
  "e1440" :"Hydroxyl propyl starch",
  "e1442" :"Hydroxy propyl distarch phosphate",
  "e1450" :"Starch sodium octenyl succinate",
  "e1451" :"Acetylated oxidised starch",
  "e1452" :"Starch aluminium Octenyl succinate",
  "e1505" :"Triethyl citrate",
  "e1517" :"Glyceryl diacetate (diacetin)",
  "e1518" :"Glyceryl triacetate",
  "e1519" :"Benzyl alcohol",
  "e1520" :"Propan-1,2-diol",
  "e1521" :"Polyethylene glycol",
};
